# Generated by Django 2.0.2 on 2018-03-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meetinginfo_contact_name_2s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetinginfo',
            old_name='contact_name_2s',
            new_name='contact_name_2',
        ),
    ]
