# Generated by Django 2.0.2 on 2018-03-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180305_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='root_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RootServer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='root_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RootServer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='service_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ServiceBody'),
        ),
        migrations.AlterField(
            model_name='servicebody',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceBody'),
        ),
        migrations.AlterField(
            model_name='servicebody',
            name='root_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RootServer'),
        ),
    ]
