# Generated by Django 2.0.2 on 2018-03-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180313_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootserver',
            name='last_successful_import',
            field=models.DateTimeField(null=True),
        ),
    ]
