# Generated by Django 2.0.2 on 2018-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180303_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetinginfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rootserver',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicebody',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
