# Generated by Django 2.0.2 on 2018-03-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180306_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
