# Generated by Django 2.0.2 on 2018-03-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180306_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproblem',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
