# Generated by Django 2.0.2 on 2018-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_servicebody_helpline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='bus_lines',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
