# Generated by Django 2.0.2 on 2018-10-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181013_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootserver',
            name='num_areas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rootserver',
            name='num_meetings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rootserver',
            name='num_regions',
            field=models.IntegerField(default=0),
        ),
    ]
