# Generated by Django 2.0.2 on 2018-10-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181013_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootserver',
            name='source_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
