# Generated by Django 2.2.2 on 2019-07-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181020_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='type',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
