# Generated by Django 2.1.5 on 2019-11-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootserver',
            name='num_zones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicebody',
            name='type',
            field=models.CharField(choices=[('AS', 'Area'), ('MA', 'Metro'), ('RS', 'Region'), ('ZF', 'Zone')], max_length=2, null=True),
        ),
    ]
