# Generated by Django 2.2.4 on 2019-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191130_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebody',
            name='type',
            field=models.CharField(choices=[('GS', 'Group Support Unit'), ('LS', 'Local Service Unit'), ('AS', 'Area'), ('MA', 'Metro'), ('RS', 'Region'), ('ZF', 'Zone')], max_length=2, null=True),
        ),
    ]
