# Generated by Django 2.2.4 on 2019-12-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_servicebody_num_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebody',
            name='num_groups',
            field=models.IntegerField(default=0),
        ),
    ]
