# Generated by Django 2.2.4 on 2019-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_servicebody_num_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootserver',
            name='num_groups',
            field=models.IntegerField(default=0),
        ),
    ]
