# Generated by Django 2.2.4 on 2020-03-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rootserver_num_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='location_info',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
