# Generated by Django 2.2.8 on 2020-03-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200315_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginfo',
            name='phone_meeting_number',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='virtual_meeting_link',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
