# Generated by Django 2.2.8 on 2020-06-23 19:28

from django.db import migrations, models
import django.db.models.deletion


def migrate_formats(apps, schema_editor):
    Format = apps.get_model('api', 'Format')
    TranslatedFormat = apps.get_model('api', 'TranslatedFormat')
    for fmt in Format.objects.all():
        TranslatedFormat.objects.create(
            key_string=fmt.key_string,
            name=fmt.name,
            description=fmt.description,
            language=fmt.language,
            format=fmt
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200322_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedFormat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_string', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(default='en', max_length=7)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Format')),
            ],
        ),
        migrations.RunPython(migrate_formats)
    ]
