# Generated by Django 2.2.8 on 2020-06-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_translatedformat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='description',
        ),
        migrations.RemoveField(
            model_name='format',
            name='key_string',
        ),
        migrations.RemoveField(
            model_name='format',
            name='language',
        ),
        migrations.RemoveField(
            model_name='format',
            name='name',
        ),
    ]
