# Generated by Django 2.2.8 on 2020-06-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200623_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedformat',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='translatedformats', to='api.Format'),
        ),
    ]
