# Generated by Django 2.2.8 on 2020-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200624_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedformat',
            name='key_string',
            field=models.CharField(max_length=20),
        ),
    ]
