# Generated by Django 2.2.8 on 2020-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200624_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginfo',
            name='virtual_meeting_additional_info',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
