# Generated by Django 2.2.13 on 2020-08-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200713_1245'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translatedformat',
            index=models.Index(fields=['format', 'language'], name='api_transla_format__afc1af_idx'),
        ),
    ]
