# Generated by Django 2.2.13 on 2020-12-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200830_1244'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='translatedformat',
            name='api_transla_format__afc1af_idx',
        ),
    ]
