# Generated by Django 2.2.13 on 2021-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201207_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='location_text',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
