# Generated by Django 2.2.13 on 2021-11-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210131_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='venue_type',
            field=models.SmallIntegerField(null=True),
        ),
    ]
