# Generated by Django 2.2.13 on 2021-11-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_meeting_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='location_text',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
